module.exports = {
  www: 'www.',
  slash: '/',
  blankString: '',
  https: 'https',
  host: 'host',
  questionMark: '?',
  hash: '#',
  slashString: '://',
  props: {
    protocol: 'protocol',
    hostname: 'hostname',
    path: 'path',
    queryString: 'queryString',
    hash: 'hash',
    persistQuery: 'persistQuery',
    persistHash: 'persistHash',
    redirectType: 'redirectType',
    pathOverride: 'pathOverride',
  },
};
