module.exports = {
  www: 'www.',
  slash: '/',
  blankString: '',
  https: 'https',
  host: 'host',
  protocolProp: 'protocol',
  hostnameProp: 'hostname',
  pathProp: 'path',
  queryStringProp: 'queryString',
  hashProp: 'hash',
  questionMark: '?',
  hashSymbol: '#',
  slashString: '://',
  persistQuery: 'persistQuery',
  persistHash: 'persistHash',
  redirectType: 'redirectType',
  pathOverride: 'pathOverride',
};
