module.exports = {
  www: 'www.',
  slash: '/',
  blankString: '',
  http: 'http',
  https: 'https',
  host: 'host',
  questionMark: '?',
  hash: '#',
  slashString: '://',
  props: {
    protocol: 'protocol',
    hostname: 'hostname',
    path: 'path',
    queryString: 'queryString',
    hash: 'hash',
    persistQueryString: 'persistQueryString',
    persistHash: 'persistHash',
    redirectCode: 'redirectCode',
    pathOverride: 'pathOverride',
  },
};
